import styles from '@/styles/Profile.module.css';
import Link from 'next/link';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export default function Profile() {
    return (
        <>
            <Head>
                <title>Your Profile</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main__container}>
                <div className={styles.banner}>
                    <Navbar />
                    <div className={styles.banner__bottom}>
                        <div className={styles.user__profile}>
                            <img src="./imgs/profileImg.png" width={200}></img>
                            <h1 className={styles.profile__name}>Jimmy Neutron</h1>
                        </div>
                    </div>
                </div>
                <div className={styles.container}>
                    <div className={styles.short__bio}>
                        <ul>
                            <li><b>UX/UI Designer</b> @ Mastercard</li>
                            <li>Vancouver, British Columbia</li>
                            <li><a href="https://www.cozy6.ca">www.cozy6.ca</a></li>
                        </ul>
                    </div>
                    <div className={styles.row}>
                        <div className={styles.column}>
                        <h2>About<hr className={styles.about__hr}></hr></h2>
                           <div className={styles.about__section}>
                            <p>I am a UX/UI designer with a passion for creating intuitive, user-friendly digital experiences. With a keen eye for design and a deep understanding of user behavior, I aim to create interfaces that seamlessly blend form and function.</p>
                           </div> 
                            <div className={styles.socials__section}>
                                <h2>Socials</h2>
                                <div className={styles.socials__icons}>
                                    <img src="./logo/social_imagery/github.png" width={55}></img>
                                    <img src="./logo/social_imagery/LI.png" width={55}></img>
                                </div>
                            </div>
                            <h2>Experience<hr className={styles.experience__hr}></hr></h2>
                            <div className={styles.experience__section}>
                                <div className={styles.experience__icons}>
                                    <img src="./logo/company_logos/mastercard.png" width={55}></img>
                                    <img src="./logo/company_logos/SAP-Logo.png" width={55}></img>
                                    <img src="./logo/company_logos/Electronic-Arts-Logo.svg.png" width={55}></img>
                                </div>
                                <div className={styles.experience__descriptions}>
                                    <ul>
                                        <li>
                                            <h4>UX/UI Designer</h4>
                                            <p><b>Mastercard</b> · Jan 2023 to Present</p>
                                        </li>
                                    </ul>
                                    <ul>
                                        <li>
                                            <h4>UX/UI Designer</h4>
                                            <p><b>SAP</b> · July 2022 to Dec 2022</p>
                                        </li>
                                    </ul>
                                    <ul>
                                        <li>
                                            <h4>UX Design Co-Op</h4>
                                            <p><b>Electronic Arts</b> · May 2022 to July 2022</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <h2>Education</h2>
                            <div className={styles.education__section}>
                                <div className={styles.education__icons}>
                                    <img src="./logo/company_logos/BCIT_logo.png" width={50}></img>
                                </div>
                                <div className={styles.education__descriptions}>
                                    <ul>
                                        <li>
                                            <h4><b>Diploma, Digital Design & Development</b></h4>
                                            <p>British Columbia Institute of Technology - Sept 2020 to May 2022</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div className={styles.column}>
                            <h2 className={styles.badges__header}>Badges<hr className={styles.badges__hr}></hr></h2>
                            <div className={styles.badges__container}>
                                <img src="./badges/badge5.png" width={50}></img>
                                <img src="./badges/badge3.png" width={50}></img>
                                <img src="./badges/badge4.png" width={50}></img>
                                <img src="./badges/badge2.png" width={50}></img>
                                <img src="./badges/badge1.png" width={50}></img>
                            </div>
                            <h2 className={styles.skills__header}>Skills<hr className={styles.skills__hr}></hr></h2>
                            <div className={styles.skills__container}>
                                <img src="./imgs/skills.png"></img>
                            </div>
                        </div>
                    </div>
                </div>
                <Footer />
            </main>
        </>
    )
}